language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t rmcaves/react-test -f ./client/Dockerfile.dev ./client

script:
    # - docker run -e CI=true rmcaves/react-test npm test
    # - docker run rmcaves/react-test npm test
    
after_success:
    - docker build -t bmcavestany/multi-client ./client
    - docker build -t bmcavestany/multi-nginx ./nginx
    - docker build -t bmcavestany/multi-server ./server
    - docker build -t bmcavestany/multi-worker ./worker
    # Log in to the dock CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push bmcavestany/multi-client
    - docker push bmcavestany/multi-nginx
    - docker push bmcavestany/multi-server
    - docker push bmcavestany/multi-worker


